### PR TITLE
Added Responsive and export Plugin management in the directive

### PR DESCRIPTION
**Pull request by Mike6gPerso**
Responsive and Export plugin can now be used from the amCharts Lib (v3)

``` javascript
var amChartOptions = {
...
    "export": {
        "enabled": true
    },
    "responsive": {
        "enabled": true,
        "addDefaultRules": true
    }
};
```

### CODE REVIEW

**Comment by GrantMStevens** [comment]
Merged. Thanks for the PR

**Comment by Mike6gPerso** [comment]
Can you be more specific ?
Version ? options ?...

**Comment by PemmasaniRajesh** [comment]
I'm using amcharts version 3.20.1 and current directive and options are:

  responsive: {
            enabled: true
        }

For the above options I've included responsive plugin(responsive.min.js) also, but it is not working :(

**Comment by Mike6gPerso** [comment]
This modification is not in a released version of amCharts-Angular

Get the master directly if you need this feature

**Comment by PemmasaniRajesh** [comment]
Yup, I'm using master version only, but no use....

**Pull request merged**
